name: Pewpew
version: '${version}'
main: gg.deepsite.pewpew.PewpewPlugin
loader: gg.deepsite.pewpew.PewpewPluginLoader
api-version: '1.21'
authors: [ ThebigTijn ]
website: https://deepsite.gg
dependencies:
  server:
    Skript:
      load: BEFORE
      required: false
    WorldGuard:
      load: BEFORE
      required: false
    CombatTagPlus:
      load: BEFORE
      required: false